spring:
  kafka:
    topics:
      resetPassword: ${RESETPASSWORD_TOPIC:user-ms-reset-password-topic}
      registration: ${REGISTRATION_TOPIC:user-ms-registration-topic}
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:${webclient.base-url}}:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        max.block.ms: 20000
        delivery.timeout.ms: 100000
    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:${webclient.base-url}}:9092
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:${webclient.base-url}}:${KAFKA_PORT:9092}
      group-id: notification-group-id
