spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: taxiapp.notifications@gmail.com
    password: crywkroexersmdty
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    templates:
      path: mail-templates
